name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: ingress-drone-explorer

jobs:
  build:
    name: Build for ${{ matrix.arch }}-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        platform:
          - apple-darwin
          - pc-windows-msvc
          - unknown-linux-gnu
        include:
          - arch: x86_64
            native: true
          - platform: apple-darwin
            os: macos
          - platform: pc-windows-msvc
            os: windows
          - platform: unknown-linux-gnu
            os: ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Setup toolchain
        run: rustup target add ${{ matrix.arch }}-${{ matrix.platform }}

      - name: Build as native
        if: matrix.native
        run: cargo build -r --target ${{ matrix.arch }}-${{ matrix.platform }}

      - name: Setup cross
        if: matrix.native != true
        run: cargo install cross
      - name: Build with cross
        if: matrix.native != true
        run: cross build -r --target ${{ matrix.arch }}-${{ matrix.platform }}

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.arch }}-${{ matrix.platform }}
          path: |
            target/${{ matrix.arch }}-${{ matrix.platform }}/release/${{ env.BINARY_NAME }}*
            !target/${{ matrix.arch }}-${{ matrix.platform }}/release/${{ env.BINARY_NAME }}.d
